import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { OverlayProvider } from "@/shared/context/OverlayContext";
import { QueryProvider } from "@/shared/context/QueryWrapper";

export const metadata: Metadata = {
	title: "3Legant",
	description: "Generated by create next app",
};

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600"],
	variable: "--font-poppins",
});


export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en' className={poppins.variable}>
			<body>
				<QueryProvider>
					<OverlayProvider>{children}</OverlayProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
