import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { OverlayProvider, QueryProvider } from "@/provider";

export const metadata: Metadata = {
	title: "3Legant",
	description: "Generated by create next app",
};

const geistPoppins = Poppins({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	variable: "--font-poppins",
});

const geistInter = Inter({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	variable: "--font-poppins",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistPoppins.variable} ${geistInter.variable} antialiased`}
			>
				<Suspense>
					<QueryProvider>
						<OverlayProvider>{children}</OverlayProvider>
					</QueryProvider>
				</Suspense>
			</body>
		</html>
	);
}
